// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/accordion.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Single: { layout: 'padded' },
  Multiple: { layout: 'padded' },
  'Hidden Until Found': { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Single: examples['Single'],
  Multiple: examples['Multiple'],
  'Hidden Until Found': examples['Hidden Until Found'],
  Reference: () => <ComponentReference slug="accordion" />,
};
