// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/aspect-ratio.examples';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Default: { layout: 'padded' },
  Square: { layout: 'padded' },
  Portrait: { layout: 'padded' },
  Preset: { layout: 'padded' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Square: examples['Square'],
  Portrait: examples['Portrait'],
  Preset: examples['Preset'],
};
