// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/bleed.examples';
import { Bleed } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Example: { layout: 'centered' },
  Side: { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Example: examples['Example'],
  Side: examples['Side'],
  Playground: () => <Playground slug="bleed" component={Bleed} name="Bleed" />,
  Reference: () => <ComponentReference slug="bleed" />,
};
