// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/collapsible.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Default: { layout: 'padded' },
  'Open by default': { layout: 'padded' },
  Disabled: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'Open by default': examples['Open by default'],
  Disabled: examples['Disabled'],
  Reference: () => <ComponentReference slug="collapsible" />,
};
