// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/container.examples';
import { Container } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Align: { layout: 'centered' },
  'As another element': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Align: examples['Align'],
  'As another element': examples['As another element'],
  Playground: () => <Playground slug="container" component={Container} name="Container" />,
  Reference: () => <ComponentReference slug="container" />,
};
