// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/grid.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Example: { layout: 'padded' },
  UniformColumns: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Example: examples['Example'],
  UniformColumns: examples['UniformColumns'],
  Reference: () => <ComponentReference slug="grid" />,
};
