// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/h-stack.examples';
import { HStack } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Example: { layout: 'padded' },
  Separator: { layout: 'padded' },
  Playground: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Example: examples['Example'],
  Separator: examples['Separator'],
  Playground: () => <Playground slug="h-stack" component={HStack} name="HStack" />,
  Reference: () => <ComponentReference slug="h-stack" />,
};
