// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/inset.examples';
import { Inset } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Example: { layout: 'padded' },
  Playground: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Example: examples['Example'],
  Playground: () => <Playground slug="inset" component={Inset} name="Inset" />,
  Reference: () => <ComponentReference slug="inset" />,
};
