// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/layout.examples';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
};

export default {
  Overview: examples['Overview'],
};
