// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/separator.examples';
import { Separator } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  Orientation: { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Color: examples['Color'],
  Orientation: examples['Orientation'],
  Playground: () => <Playground slug="separator" component={Separator} name="Separator" />,
  Reference: () => <ComponentReference slug="separator" />,
};
