// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/sidebar.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'fullscreen' },
  Default: { layout: 'fullscreen' },
  'Collapse to icon rail': { layout: 'fullscreen' },
  'Not collapsible': { layout: 'fullscreen' },
  'Sub-menus, actions, badges & skeletons': { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'Collapse to icon rail': examples['Collapse to icon rail'],
  'Not collapsible': examples['Not collapsible'],
  'Sub-menus, actions, badges & skeletons': examples['Sub-menus, actions, badges & skeletons'],
  Reference: () => <ComponentReference slug="sidebar" />,
};
