// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/v-stack.examples';
import { VStack } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Example: { layout: 'padded' },
  Playground: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Example: examples['Example'],
  Playground: () => <Playground slug="v-stack" component={VStack} name="VStack" />,
  Reference: () => <ComponentReference slug="v-stack" />,
};
