// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../../examples/date-picker.examples';
import { DatePicker } from 'ljkui';
import { Playground } from '../../../fixture-support/playground';
import { ComponentReference } from '../../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Sizes: { layout: 'centered' },
  Custom: { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Sizes: examples['Sizes'],
  Custom: examples['Custom'],
  Playground: () => <Playground slug="date-picker" component={DatePicker} name="DatePicker" />,
  Reference: () => <ComponentReference slug="date-picker" />,
};
