// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../../examples/date-field.examples';
import { DateField } from 'ljkui';
import { Playground } from '../../../fixture-support/playground';
import { ComponentReference } from '../../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Size: { layout: 'centered' },
  MinValue: { layout: 'centered' },
  'With time': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  MinValue: examples['MinValue'],
  'With time': examples['With time'],
  Playground: () => <Playground slug="date-field" component={DateField} name="DateField" />,
  Reference: () => <ComponentReference slug="date-field" />,
};
