// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../../examples/range-calendar.examples';
import { ComponentReference } from '../../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Disabled: { layout: 'centered' },
  'Unavailable Dates': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Disabled: examples['Disabled'],
  'Unavailable Dates': examples['Unavailable Dates'],
  Reference: () => <ComponentReference slug="range-calendar" />,
};
