#!/usr/bin/env bun
/**
 * Generates (and guards) `fixture-support/prebundle.ts` — the `optimizeDeps.include` list.
 *
 * The library imports ~36 `@base-ui/react/*` subpaths. Without pre-bundling, Vite's dep
 * optimizer discovers each one lazily the first time you open the component that uses it,
 * and every discovery triggers a re-optimize plus a full page reload mid-browse. The list
 * used to be a hand-maintained array in vite.config.ts with a comment telling you to
 * regenerate it by grep — which is exactly the drift this repo already gates elsewhere.
 *
 *   bun run scripts/gen-prebundle.ts            # rewrite the list from the sources
 *   bun run scripts/gen-prebundle.ts --check    # fail instead of writing (CI)
 *
 * The scanned set is every bare (non-relative) import specifier in `src/`, intersected with
 * the package's real dependencies, plus a few entry points nothing imports by name.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { emit } from './emit.ts';
import { join } from 'node:path';
import pkg from '../package.json' with { type: 'json' };

const packageRoot = join(import.meta.dirname, '..');
const srcDir = join(packageRoot, 'src');
const target = join(packageRoot, 'fixture-support', 'prebundle.ts');

/**
 * Entry points the scan cannot see: React's runtime entries are injected by the JSX
 * transform rather than imported by name, and the explorer itself mounts through
 * `react-dom/client`.
 */
const ALWAYS = ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime', 'react/jsx-dev-runtime'];

/**
 * Only pre-bundle things the package actually depends on. A peer the consumer may not have
 * installed must not be forced into the optimizer, or a fresh clone without it fails to boot.
 */
const installed = new Set([...Object.keys(pkg.dependencies ?? {}), ...Object.keys(pkg.devDependencies ?? {})]);

/**
 * Optional peers are installed here for development but absent in a real consumer. Forcing
 * them through the optimizer on boot costs every `bun run dev` a few seconds for modules
 * almost nobody opens.
 */
const OPTIONAL_PEERS = new Set(
  Object.entries(pkg.peerDependenciesMeta ?? {})
    .filter(([, meta]) => (meta as { optional?: boolean }).optional)
    .map(([name]) => name),
);

/** `@scope/name/deep/path` → `@scope/name`; `name/deep` → `name`. */
function packageName(specifier: string): string {
  const parts = specifier.split('/');
  return specifier.startsWith('@') ? parts.slice(0, 2).join('/') : parts[0];
}

function sourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...sourceFiles(full));
    } else if (/\.tsx?$/.test(entry) && !entry.endsWith('.d.ts')) {
      out.push(full);
    }
  }
  return out;
}

const specifiers = new Set(ALWAYS);
for (const file of sourceFiles(srcDir)) {
  /*
   * Type-only statements are erased at compile time, so their specifier is never fetched at
   * runtime. Pre-bundling one asks the optimizer to resolve a path that may hold nothing but
   * declarations (`credit-card-type/dist/types`), which fails the boot.
   */
  const source = readFileSync(file, 'utf8').replace(/\b(?:import|export)\s+type\s[^;]*;/g, '');

  // `from '…'` covers static imports and re-exports; `import('…')` covers dynamic ones.
  for (const match of source.matchAll(/(?:from|import)\s*\(?\s*['"]([^'".][^'"]*)['"]/g)) {
    const specifier = match[1];
    // Bare specifiers only — a relative or absolute path is our own source.
    if (specifier.startsWith('.') || specifier.startsWith('/')) continue;
    // `node:` builtins are never bundled, and the tailwind plugin is not part of the runtime.
    if (specifier.startsWith('node:') || specifier.startsWith('tailwindcss')) continue;
    const name = packageName(specifier);
    if (!installed.has(name) || OPTIONAL_PEERS.has(name)) continue;
    specifiers.add(specifier);
  }
}

const sorted = [...specifiers].sort();

const contents = `// GENERATED by scripts/gen-prebundle.ts — do not edit. Run \`bun run generate:prebundle\`.
/*
 * Every heavy leaf dependency the components reach for, pre-bundled by Vite so browsing the
 * explorer never stalls on a lazy re-optimize plus a full page reload. See the script for
 * how the list is derived; \`check:prebundle\` fails the build if it drifts.
 */
export const PREBUNDLE = [
${sorted.map((s) => `  '${s}',`).join('\n')}
];
`;

emit(target, contents, {
  regenerate: 'bun run generate:prebundle',
  detail: `  ${sorted.length} bare import specifiers were derived from src/.`,
});
