// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/button-group.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  'With text segment': { layout: 'centered' },
  'With separator': { layout: 'centered' },
  Vertical: { layout: 'centered' },
  Sizes: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  'With text segment': examples['With text segment'],
  'With separator': examples['With separator'],
  Vertical: examples['Vertical'],
  Sizes: examples['Sizes'],
  Reference: () => <ComponentReference slug="button-group" />,
};
