// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/combobox.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Multiple: { layout: 'centered' },
  Grouped: { layout: 'centered' },
  CustomItems: { layout: 'centered' },
  ClearButton: { layout: 'centered' },
  InputInsidePopup: { layout: 'centered' },
  'Disabled & Read Only': { layout: 'centered' },
  'Auto Highlight': { layout: 'centered' },
  'Form Validation': { layout: 'centered' },
  'Many Items': { layout: 'centered' },
  Empty: { layout: 'centered' },
  TriggerOnly: { layout: 'centered' },
  'Async Search (Single)': { layout: 'centered' },
  'Async Search (Multiple)': { layout: 'centered' },
  'Loop Focus': { layout: 'centered' },
  Creatable: { layout: 'centered' },
  'Empty State': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Multiple: examples['Multiple'],
  Grouped: examples['Grouped'],
  CustomItems: examples['CustomItems'],
  ClearButton: examples['ClearButton'],
  InputInsidePopup: examples['InputInsidePopup'],
  'Disabled & Read Only': examples['Disabled & Read Only'],
  'Auto Highlight': examples['Auto Highlight'],
  'Form Validation': examples['Form Validation'],
  'Many Items': examples['Many Items'],
  Empty: examples['Empty'],
  TriggerOnly: examples['TriggerOnly'],
  'Async Search (Single)': examples['Async Search (Single)'],
  'Async Search (Multiple)': examples['Async Search (Multiple)'],
  'Loop Focus': examples['Loop Focus'],
  Creatable: examples['Creatable'],
  'Empty State': examples['Empty State'],
  Reference: () => <ComponentReference slug="combobox" />,
};
