// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/filter-chip.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  'Read Only': { layout: 'centered' },
  'Input Ref': { layout: 'centered' },
  'Form with value & uncheckedValue': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Size: examples['Size'],
  Color: examples['Color'],
  'Read Only': examples['Read Only'],
  'Input Ref': examples['Input Ref'],
  'Form with value & uncheckedValue': examples['Form with value & uncheckedValue'],
  Reference: () => <ComponentReference slug="filter-chip" />,
};
