// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/icon-button.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Variant: { layout: 'centered' },
  Color: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  Loading: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Variant: examples['Variant'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  Loading: examples['Loading'],
  Reference: () => <ComponentReference slug="icon-button" />,
};
