// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/input-group.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  'With unit': { layout: 'centered' },
  Sizes: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  'With unit': examples['With unit'],
  Sizes: examples['Sizes'],
  Reference: () => <ComponentReference slug="input-group" />,
};
