// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/number-field.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Variant: { layout: 'centered' },
  'Button Layout': { layout: 'centered' },
  'With Slot': { layout: 'centered' },
  Color: { layout: 'centered' },
  'Min / Max': { layout: 'centered' },
  'Allow Out of Range': { layout: 'centered' },
  'Step Configuration': { layout: 'centered' },
  'format (Intl.NumberFormatOptions)': { layout: 'centered' },
  Disabled: { layout: 'centered' },
  ReadOnly: { layout: 'centered' },
  'Disabled vs ReadOnly (Accessibility)': { layout: 'centered' },
  Controlled: { layout: 'centered' },
  'onValueChange vs onValueCommitted': { layout: 'centered' },
  'Input Ref': { layout: 'centered' },
  'Form Submission': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Variant: examples['Variant'],
  'Button Layout': examples['Button Layout'],
  'With Slot': examples['With Slot'],
  Color: examples['Color'],
  'Min / Max': examples['Min / Max'],
  'Allow Out of Range': examples['Allow Out of Range'],
  'Step Configuration': examples['Step Configuration'],
  'format (Intl.NumberFormatOptions)': examples['format (Intl.NumberFormatOptions)'],
  Disabled: examples['Disabled'],
  ReadOnly: examples['ReadOnly'],
  'Disabled vs ReadOnly (Accessibility)': examples['Disabled vs ReadOnly (Accessibility)'],
  Controlled: examples['Controlled'],
  'onValueChange vs onValueCommitted': examples['onValueChange vs onValueCommitted'],
  'Input Ref': examples['Input Ref'],
  'Form Submission': examples['Form Submission'],
  Reference: () => <ComponentReference slug="number-field" />,
};
