// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/radio-group.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Composed: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  'Alignment with text': { layout: 'centered' },
  'Disabled (Group)': { layout: 'centered' },
  'Disabled (Single Item)': { layout: 'centered' },
  'Input Ref (Group)': { layout: 'centered' },
  'Input Ref (Item)': { layout: 'centered' },
  'onValueChange (TypeScript)': { layout: 'centered' },
  'onValueChange (Event Details)': { layout: 'centered' },
  'Form Name': { layout: 'centered' },
  'Object Values': { layout: 'centered' },
  'Type-Safe Values': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Composed: examples['Composed'],
  Size: examples['Size'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  'Alignment with text': examples['Alignment with text'],
  'Disabled (Group)': examples['Disabled (Group)'],
  'Disabled (Single Item)': examples['Disabled (Single Item)'],
  'Input Ref (Group)': examples['Input Ref (Group)'],
  'Input Ref (Item)': examples['Input Ref (Item)'],
  'onValueChange (TypeScript)': examples['onValueChange (TypeScript)'],
  'onValueChange (Event Details)': examples['onValueChange (Event Details)'],
  'Form Name': examples['Form Name'],
  'Object Values': examples['Object Values'],
  'Type-Safe Values': examples['Type-Safe Values'],
  Reference: () => <ComponentReference slug="radio-group" />,
};
