// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/radio-button-group.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  HighContrast: { layout: 'centered' },
  WithCard: { layout: 'centered' },
  Color: { layout: 'centered' },
  'Disabled (Group)': { layout: 'centered' },
  'Disabled (Single Item)': { layout: 'centered' },
  'onValueChange (TypeScript)': { layout: 'centered' },
  'onValueChange (Event Details)': { layout: 'centered' },
  'Form Name': { layout: 'centered' },
  'Input Ref (Group)': { layout: 'centered' },
  'Type-Safe Values': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  HighContrast: examples['HighContrast'],
  WithCard: examples['WithCard'],
  Color: examples['Color'],
  'Disabled (Group)': examples['Disabled (Group)'],
  'Disabled (Single Item)': examples['Disabled (Single Item)'],
  'onValueChange (TypeScript)': examples['onValueChange (TypeScript)'],
  'onValueChange (Event Details)': examples['onValueChange (Event Details)'],
  'Form Name': examples['Form Name'],
  'Input Ref (Group)': examples['Input Ref (Group)'],
  'Type-Safe Values': examples['Type-Safe Values'],
  Reference: () => <ComponentReference slug="radio-button-group" />,
};
