// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/toggle.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Variants: { layout: 'centered' },
  Sizes: { layout: 'centered' },
  Controlled: { layout: 'centered' },
  Disabled: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Variants: examples['Variants'],
  Sizes: examples['Sizes'],
  Controlled: examples['Controlled'],
  Disabled: examples['Disabled'],
  Reference: () => <ComponentReference slug="toggle" />,
};
