// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { DEFAULT_FIXTURE } from 'uaight';
import Content, { frontmatter } from '../../guides/forms.mdx';
import { Guide } from '../../fixture-support/guide';

export const fileMeta = { order: 8 };

export const fixtureMeta = {
  [DEFAULT_FIXTURE]: { title: '9. Forms & Field Binding', layout: 'fullscreen' },
};

export default () => <Guide content={Content} frontmatter={frontmatter} />;
