/**
 * @heroicons/react (24px outline set) adapter. Importing this module registers it:
 *
 *   import 'ljkui/icons/heroicons';
 *
 * Or scope it with `<IconProvider library={heroiconsAdapter}>`.
 *
 * GENERATED FILE — do not edit by hand. Edit `scripts/icon-map.ts` and run
 * `bun run generate:icon-adapters`.
 */
import {
  AdjustmentsHorizontalIcon,
  ArchiveBoxIcon,
  ArrowDownIcon,
  ArrowDownTrayIcon,
  ArrowLeftEndOnRectangleIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpIcon,
  ArrowUpTrayIcon,
  AtSymbolIcon,
  Bars3Icon,
  Battery100Icon,
  BellIcon,
  BoltIcon,
  BookmarkIcon,
  BugAntIcon,
  CalendarIcon,
  CameraIcon,
  ChatBubbleOvalLeftIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClockIcon,
  CloudIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  CreditCardIcon,
  CubeIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FaceSmileIcon,
  FireIcon,
  FlagIcon,
  FolderIcon,
  FunnelIcon,
  GiftIcon,
  GlobeAltIcon,
  HandThumbDownIcon,
  HandThumbUpIcon,
  HashtagIcon,
  HeartIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  KeyIcon,
  LinkIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MicrophoneIcon,
  MinusIcon,
  MoonIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseIcon,
  PencilIcon,
  PhoneIcon,
  PhotoIcon,
  PlayIcon,
  PlusIcon,
  PrinterIcon,
  QuestionMarkCircleIcon,
  ScissorsIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShoppingCartIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  Squares2X2Icon,
  StarIcon,
  SunIcon,
  SwatchIcon,
  TagIcon,
  TrashIcon,
  TrophyIcon,
  TruckIcon,
  UserIcon,
  UsersIcon,
  VideoCameraIcon,
  WifiIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const heroiconsAdapter: IconAdapter = {
  name: 'heroicons',
  icons: {
    AlertCircle: ExclamationCircleIcon,
    Archive: ArchiveBoxIcon,
    ArrowDown: ArrowDownIcon,
    ArrowLeft: ArrowLeftIcon,
    ArrowRight: ArrowRightIcon,
    ArrowUp: ArrowUpIcon,
    AtSign: AtSymbolIcon,
    Battery: Battery100Icon,
    Bell: BellIcon,
    Bookmark: BookmarkIcon,
    Brush: PaintBrushIcon,
    Bug: BugAntIcon,
    Calendar: CalendarIcon,
    Camera: CameraIcon,
    Check: CheckIcon,
    ChevronDown: ChevronDownIcon,
    ChevronLeft: ChevronLeftIcon,
    ChevronRight: ChevronRightIcon,
    ChevronUp: ChevronUpIcon,
    Clock: ClockIcon,
    Close: XMarkIcon,
    Cloud: CloudIcon,
    Code: CodeBracketIcon,
    Copy: DocumentDuplicateIcon,
    CreditCard: CreditCardIcon,
    Database: CircleStackIcon,
    DotsHorizontal: EllipsisHorizontalIcon,
    DotsVertical: EllipsisVerticalIcon,
    Download: ArrowDownTrayIcon,
    Edit: PencilIcon,
    ExternalLink: ArrowTopRightOnSquareIcon,
    Eye: EyeIcon,
    EyeOff: EyeSlashIcon,
    File: DocumentIcon,
    Filter: FunnelIcon,
    Flag: FlagIcon,
    Flame: FireIcon,
    Folder: FolderIcon,
    Gift: GiftIcon,
    Globe: GlobeAltIcon,
    Hash: HashtagIcon,
    Heart: HeartIcon,
    HelpCircle: QuestionMarkCircleIcon,
    Home: HomeIcon,
    Image: PhotoIcon,
    Inbox: InboxIcon,
    Info: InformationCircleIcon,
    Key: KeyIcon,
    LayoutGrid: Squares2X2Icon,
    Link: LinkIcon,
    List: ListBulletIcon,
    Lock: LockClosedIcon,
    LogIn: ArrowLeftEndOnRectangleIcon,
    LogOut: ArrowRightStartOnRectangleIcon,
    Mail: EnvelopeIcon,
    MapPin: MapPinIcon,
    Menu: Bars3Icon,
    Message: ChatBubbleOvalLeftIcon,
    Mic: MicrophoneIcon,
    Minus: MinusIcon,
    Moon: MoonIcon,
    Package: CubeIcon,
    Palette: SwatchIcon,
    Paperclip: PaperClipIcon,
    Pause: PauseIcon,
    Phone: PhoneIcon,
    Play: PlayIcon,
    Plus: PlusIcon,
    Printer: PrinterIcon,
    Refresh: ArrowPathIcon,
    Scissors: ScissorsIcon,
    Search: MagnifyingGlassIcon,
    Send: PaperAirplaneIcon,
    Server: ServerIcon,
    Settings: Cog6ToothIcon,
    Share: ShareIcon,
    Shield: ShieldCheckIcon,
    ShoppingCart: ShoppingCartIcon,
    Sliders: AdjustmentsHorizontalIcon,
    Smile: FaceSmileIcon,
    Star: StarIcon,
    Sun: SunIcon,
    Tag: TagIcon,
    Terminal: CommandLineIcon,
    ThumbsDown: HandThumbDownIcon,
    ThumbsUp: HandThumbUpIcon,
    Trash: TrashIcon,
    Trophy: TrophyIcon,
    Truck: TruckIcon,
    Unlock: LockOpenIcon,
    Upload: ArrowUpTrayIcon,
    User: UserIcon,
    Users: UsersIcon,
    Video: VideoCameraIcon,
    Volume: SpeakerWaveIcon,
    VolumeOff: SpeakerXMarkIcon,
    Warning: ExclamationTriangleIcon,
    Wifi: WifiIcon,
    Zap: BoltIcon,
  },
};

registerIconAdapter(heroiconsAdapter);
