/**
 * @phosphor-icons/react adapter. Importing this module registers it:
 *
 *   import 'ljkui/icons/phosphor';
 *
 * Or scope it with `<IconProvider library={phosphorAdapter}>`.
 *
 * GENERATED FILE — do not edit by hand. Edit `scripts/icon-map.ts` and run
 * `bun run generate:icon-adapters`.
 */
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowsClockwise,
  At,
  BatteryFull,
  Bell,
  BookmarkSimple,
  Bug,
  Calendar,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChatCircle,
  Check,
  Clock,
  Cloud,
  Code,
  Copy,
  CreditCard,
  Database,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Envelope,
  Eye,
  EyeSlash,
  File,
  Fire,
  Flag,
  Folder,
  Funnel,
  Gear,
  Gift,
  Globe,
  HardDrives,
  Hash,
  Heart,
  House,
  Image,
  Info,
  Key,
  Lightning,
  Link,
  List,
  ListBullets,
  Lock,
  LockOpen,
  MagnifyingGlass,
  MapPin,
  Microphone,
  Minus,
  Moon,
  Package,
  PaintBrush,
  Palette,
  PaperPlaneTilt,
  Paperclip,
  Pause,
  PencilSimple,
  Phone,
  Play,
  Plus,
  Printer,
  Question,
  Scissors,
  ShareNetwork,
  Shield,
  ShoppingCart,
  SignIn,
  SignOut,
  Sliders,
  Smiley,
  SpeakerHigh,
  SpeakerX,
  SquaresFour,
  Star,
  Sun,
  Tag,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Trash,
  Tray,
  Trophy,
  Truck,
  UploadSimple,
  User,
  Users,
  VideoCamera,
  Warning,
  WarningCircle,
  WifiHigh,
  X,
} from '@phosphor-icons/react';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const phosphorAdapter: IconAdapter = {
  name: 'phosphor',
  icons: {
    AlertCircle: WarningCircle,
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    AtSign: At,
    Battery: BatteryFull,
    Bell,
    Bookmark: BookmarkSimple,
    Brush: PaintBrush,
    Bug,
    Calendar,
    Camera,
    Check,
    ChevronDown: CaretDown,
    ChevronLeft: CaretLeft,
    ChevronRight: CaretRight,
    ChevronUp: CaretUp,
    Clock,
    Close: X,
    Cloud,
    Code,
    Copy,
    CreditCard,
    Database,
    DotsHorizontal: DotsThree,
    DotsVertical: DotsThreeVertical,
    Download: DownloadSimple,
    Edit: PencilSimple,
    ExternalLink: ArrowSquareOut,
    Eye,
    EyeOff: EyeSlash,
    File,
    Filter: Funnel,
    Flag,
    Flame: Fire,
    Folder,
    Gift,
    Globe,
    Hash,
    Heart,
    HelpCircle: Question,
    Home: House,
    Image,
    Inbox: Tray,
    Info,
    Key,
    LayoutGrid: SquaresFour,
    Link,
    List: ListBullets,
    Lock,
    LogIn: SignIn,
    LogOut: SignOut,
    Mail: Envelope,
    MapPin,
    Menu: List,
    Message: ChatCircle,
    Mic: Microphone,
    Minus,
    Moon,
    Package,
    Palette,
    Paperclip,
    Pause,
    Phone,
    Play,
    Plus,
    Printer,
    Refresh: ArrowsClockwise,
    Scissors,
    Search: MagnifyingGlass,
    Send: PaperPlaneTilt,
    Server: HardDrives,
    Settings: Gear,
    Share: ShareNetwork,
    Shield,
    ShoppingCart,
    Sliders,
    Smile: Smiley,
    Star,
    Sun,
    Tag,
    Terminal,
    ThumbsDown,
    ThumbsUp,
    Trash,
    Trophy,
    Truck,
    Unlock: LockOpen,
    Upload: UploadSimple,
    User,
    Users,
    Video: VideoCamera,
    Volume: SpeakerHigh,
    VolumeOff: SpeakerX,
    Warning,
    Wifi: WifiHigh,
    Zap: Lightning,
  },
};

registerIconAdapter(phosphorAdapter);
