/**
 * @tabler/icons-react adapter. Importing this module registers it:
 *
 *   import 'ljkui/icons/tabler';
 *
 * Or scope it with `<IconProvider library={tablerAdapter}>`.
 *
 * GENERATED FILE — do not edit by hand. Edit `scripts/icon-map.ts` and run
 * `bun run generate:icon-adapters`.
 */
import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArchive,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconAt,
  IconBattery4,
  IconBell,
  IconBolt,
  IconBookmark,
  IconBrush,
  IconBug,
  IconCalendar,
  IconCamera,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconClock,
  IconCloud,
  IconCode,
  IconCopy,
  IconCreditCard,
  IconDatabase,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFilter,
  IconFlag,
  IconFlame,
  IconFolder,
  IconGift,
  IconHash,
  IconHeart,
  IconHelpCircle,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLayoutGrid,
  IconLink,
  IconList,
  IconLock,
  IconLockOpen,
  IconLogin,
  IconLogout,
  IconMail,
  IconMapPin,
  IconMenu2,
  IconMessageCircle,
  IconMicrophone,
  IconMinus,
  IconMoodSmile,
  IconMoon,
  IconPackage,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlus,
  IconPrinter,
  IconRefresh,
  IconScissors,
  IconSearch,
  IconSend,
  IconServer,
  IconSettings,
  IconShare,
  IconShield,
  IconShoppingCart,
  IconStar,
  IconSun,
  IconTag,
  IconTerminal,
  IconThumbDown,
  IconThumbUp,
  IconTrash,
  IconTrophy,
  IconTruck,
  IconUpload,
  IconUser,
  IconUsers,
  IconVideo,
  IconVolume,
  IconVolumeOff,
  IconWifi,
  IconWorld,
  IconX,
} from '@tabler/icons-react';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const tablerAdapter: IconAdapter = {
  name: 'tabler',
  icons: {
    AlertCircle: IconAlertCircle,
    Archive: IconArchive,
    ArrowDown: IconArrowDown,
    ArrowLeft: IconArrowLeft,
    ArrowRight: IconArrowRight,
    ArrowUp: IconArrowUp,
    AtSign: IconAt,
    Battery: IconBattery4,
    Bell: IconBell,
    Bookmark: IconBookmark,
    Brush: IconBrush,
    Bug: IconBug,
    Calendar: IconCalendar,
    Camera: IconCamera,
    Check: IconCheck,
    ChevronDown: IconChevronDown,
    ChevronLeft: IconChevronLeft,
    ChevronRight: IconChevronRight,
    ChevronUp: IconChevronUp,
    Clock: IconClock,
    Close: IconX,
    Cloud: IconCloud,
    Code: IconCode,
    Copy: IconCopy,
    CreditCard: IconCreditCard,
    Database: IconDatabase,
    DotsHorizontal: IconDots,
    DotsVertical: IconDotsVertical,
    Download: IconDownload,
    Edit: IconPencil,
    ExternalLink: IconExternalLink,
    Eye: IconEye,
    EyeOff: IconEyeOff,
    File: IconFile,
    Filter: IconFilter,
    Flag: IconFlag,
    Flame: IconFlame,
    Folder: IconFolder,
    Gift: IconGift,
    Globe: IconWorld,
    Hash: IconHash,
    Heart: IconHeart,
    HelpCircle: IconHelpCircle,
    Home: IconHome,
    Image: IconPhoto,
    Inbox: IconInbox,
    Info: IconInfoCircle,
    Key: IconKey,
    LayoutGrid: IconLayoutGrid,
    Link: IconLink,
    List: IconList,
    Lock: IconLock,
    LogIn: IconLogin,
    LogOut: IconLogout,
    Mail: IconMail,
    MapPin: IconMapPin,
    Menu: IconMenu2,
    Message: IconMessageCircle,
    Mic: IconMicrophone,
    Minus: IconMinus,
    Moon: IconMoon,
    Package: IconPackage,
    Palette: IconPalette,
    Paperclip: IconPaperclip,
    Pause: IconPlayerPause,
    Phone: IconPhone,
    Play: IconPlayerPlay,
    Plus: IconPlus,
    Printer: IconPrinter,
    Refresh: IconRefresh,
    Scissors: IconScissors,
    Search: IconSearch,
    Send: IconSend,
    Server: IconServer,
    Settings: IconSettings,
    Share: IconShare,
    Shield: IconShield,
    ShoppingCart: IconShoppingCart,
    Sliders: IconAdjustmentsHorizontal,
    Smile: IconMoodSmile,
    Star: IconStar,
    Sun: IconSun,
    Tag: IconTag,
    Terminal: IconTerminal,
    ThumbsDown: IconThumbDown,
    ThumbsUp: IconThumbUp,
    Trash: IconTrash,
    Trophy: IconTrophy,
    Truck: IconTruck,
    Unlock: IconLockOpen,
    Upload: IconUpload,
    User: IconUser,
    Users: IconUsers,
    Video: IconVideo,
    Volume: IconVolume,
    VolumeOff: IconVolumeOff,
    Warning: IconAlertTriangle,
    Wifi: IconWifi,
    Zap: IconBolt,
  },
};

registerIconAdapter(tablerAdapter);
