// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/code.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Variant: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Variant: examples['Variant'],
  Size: examples['Size'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  Reference: () => <ComponentReference slug="code" />,
};
