// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/heading.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  Align: { layout: 'centered' },
  Trim: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Color: examples['Color'],
  Align: examples['Align'],
  Trim: examples['Trim'],
  'High Contrast': examples['High Contrast'],
  Reference: () => <ComponentReference slug="heading" />,
};
