// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/link.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  Underline: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  'As Button': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Color: examples['Color'],
  Underline: examples['Underline'],
  'High Contrast': examples['High Contrast'],
  'As Button': examples['As Button'],
  Reference: () => <ComponentReference slug="link" />,
};
