// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/link.examples';
import { Link } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  Underline: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  'As Button': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Color: examples['Color'],
  Underline: examples['Underline'],
  'High Contrast': examples['High Contrast'],
  'As Button': examples['As Button'],
  Playground: () => <Playground slug="link" component={Link} name="Link" />,
  Reference: () => <ComponentReference slug="link" />,
};
