// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/text.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Size: { layout: 'centered' },
  Weight: { layout: 'centered' },
  Color: { layout: 'centered' },
  Align: { layout: 'centered' },
  Trim: { layout: 'centered' },
  Formatting: { layout: 'centered' },
  'With form controls': { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  'As Form Label': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Weight: examples['Weight'],
  Color: examples['Color'],
  Align: examples['Align'],
  Trim: examples['Trim'],
  Formatting: examples['Formatting'],
  'With form controls': examples['With form controls'],
  'High Contrast': examples['High Contrast'],
  'As Form Label': examples['As Form Label'],
  Reference: () => <ComponentReference slug="text" />,
};
