// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/chart.examples';
import { Chart } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'fullscreen' },
  Default: { layout: 'fullscreen' },
  'Custom label': { layout: 'fullscreen' },
  Animated: { layout: 'fullscreen' },
  Playground: { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'Custom label': examples['Custom label'],
  Animated: examples['Animated'],
  Playground: () => <Playground slug="chart" component={Chart} name="Chart" />,
  Reference: () => <ComponentReference slug="chart" />,
};
