// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/data-table.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'fullscreen' },
  Size: { layout: 'fullscreen' },
  Orientation: { layout: 'fullscreen' },
  Color: { layout: 'fullscreen' },
  'High Contrast': { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Orientation: examples['Orientation'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  Reference: () => <ComponentReference slug="data-table" />,
};
