// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/table.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Variant: { layout: 'fullscreen' },
  TableFooter: { layout: 'fullscreen' },
  HorizontalScroll: { layout: 'fullscreen' },
  TanstackTable: { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Variant: examples['Variant'],
  TableFooter: examples['TableFooter'],
  HorizontalScroll: examples['HorizontalScroll'],
  TanstackTable: examples['TanstackTable'],
  Reference: () => <ComponentReference slug="table" />,
};
