// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples, playgroundChildren } from '../../examples/table.examples';
import { Table } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'fullscreen' },
  Variant: { layout: 'fullscreen' },
  TableFooter: { layout: 'fullscreen' },
  HorizontalScroll: { layout: 'fullscreen' },
  TanstackTable: { layout: 'fullscreen' },
  Playground: { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Variant: examples['Variant'],
  TableFooter: examples['TableFooter'],
  HorizontalScroll: examples['HorizontalScroll'],
  TanstackTable: examples['TanstackTable'],
  Playground: () => (
    <Playground slug="table" component={Table.Root} name="Table.Root" renderChildren={() => playgroundChildren} />
  ),
  Reference: () => <ComponentReference slug="table" />,
};
