// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/alert-dialog.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Sizes: { layout: 'centered' },
  'With inset content': { layout: 'centered' },
  'Using Close Component': { layout: 'centered' },
  'Detached Triggers': { layout: 'centered' },
  'Multiple Triggers with Payload': { layout: 'centered' },
  'Controlled Mode': { layout: 'centered' },
  'Actions Ref': { layout: 'centered' },
  'Initial Focus': { layout: 'centered' },
  'Final Focus': { layout: 'centered' },
  'Open Change Complete': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Sizes: examples['Sizes'],
  'With inset content': examples['With inset content'],
  'Using Close Component': examples['Using Close Component'],
  'Detached Triggers': examples['Detached Triggers'],
  'Multiple Triggers with Payload': examples['Multiple Triggers with Payload'],
  'Controlled Mode': examples['Controlled Mode'],
  'Actions Ref': examples['Actions Ref'],
  'Initial Focus': examples['Initial Focus'],
  'Final Focus': examples['Final Focus'],
  'Open Change Complete': examples['Open Change Complete'],
  Reference: () => <ComponentReference slug="alert-dialog" />,
};
