// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/avatar.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Shape: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  HighContrast: { layout: 'centered' },
  Fallback: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Shape: examples['Shape'],
  Size: examples['Size'],
  Color: examples['Color'],
  HighContrast: examples['HighContrast'],
  Fallback: examples['Fallback'],
  Reference: () => <ComponentReference slug="avatar" />,
};
