// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/lightbox.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'fullscreen' },
  WithThumbnails: { layout: 'fullscreen' },
  Controlled: { layout: 'fullscreen' },
  ImperativeAPI: { layout: 'fullscreen' },
  LazyLoading: { layout: 'fullscreen' },
  WithScrollGallery: { layout: 'fullscreen' },
  'Within Article': { layout: 'fullscreen' },
  'Social Feed': { layout: 'fullscreen' },
  'Real Estate Listing': { layout: 'fullscreen' },
  'Color Palette': { layout: 'fullscreen' },
  'Design File Inspector': { layout: 'fullscreen' },
  'Film Trailers': { layout: 'fullscreen' },
  'Team Directory': { layout: 'fullscreen' },
  'Lifecycle Callbacks': { layout: 'fullscreen' },
  'With Zoom': { layout: 'fullscreen' },
  'Scroll Gallery with Zoom': { layout: 'fullscreen' },
  'morphTo Setting': { layout: 'fullscreen' },
  'Text Message': { layout: 'fullscreen' },
  'Perfect Morph': { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  WithThumbnails: examples['WithThumbnails'],
  Controlled: examples['Controlled'],
  ImperativeAPI: examples['ImperativeAPI'],
  LazyLoading: examples['LazyLoading'],
  WithScrollGallery: examples['WithScrollGallery'],
  'Within Article': examples['Within Article'],
  'Social Feed': examples['Social Feed'],
  'Real Estate Listing': examples['Real Estate Listing'],
  'Color Palette': examples['Color Palette'],
  'Design File Inspector': examples['Design File Inspector'],
  'Film Trailers': examples['Film Trailers'],
  'Team Directory': examples['Team Directory'],
  'Lifecycle Callbacks': examples['Lifecycle Callbacks'],
  'With Zoom': examples['With Zoom'],
  'Scroll Gallery with Zoom': examples['Scroll Gallery with Zoom'],
  'morphTo Setting': examples['morphTo Setting'],
  'Text Message': examples['Text Message'],
  'Perfect Morph': examples['Perfect Morph'],
  Reference: () => <ComponentReference slug="lightbox" />,
};
