// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/popover.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Variant: { layout: 'centered' },
  'With inset content': { layout: 'centered' },
  'Opening on Hover': { layout: 'centered' },
  'Detached Triggers': { layout: 'centered' },
  'Multiple Triggers with Payload': { layout: 'centered' },
  'Controlled Mode with Multiple Triggers': { layout: 'centered' },
  'Custom Anchor': { layout: 'centered' },
  'Disable Anchor Tracking': { layout: 'centered' },
  Sticky: { layout: 'centered' },
  'Collision Boundary': { layout: 'centered' },
  'Collision Avoidance': { layout: 'centered' },
  'Modal Behavior': { layout: 'centered' },
  'Open Change Callbacks': { layout: 'centered' },
  'Actions Ref': { layout: 'centered' },
  'Final Focus': { layout: 'centered' },
  'Initial Focus': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Variant: examples['Variant'],
  'With inset content': examples['With inset content'],
  'Opening on Hover': examples['Opening on Hover'],
  'Detached Triggers': examples['Detached Triggers'],
  'Multiple Triggers with Payload': examples['Multiple Triggers with Payload'],
  'Controlled Mode with Multiple Triggers': examples['Controlled Mode with Multiple Triggers'],
  'Custom Anchor': examples['Custom Anchor'],
  'Disable Anchor Tracking': examples['Disable Anchor Tracking'],
  Sticky: examples['Sticky'],
  'Collision Boundary': examples['Collision Boundary'],
  'Collision Avoidance': examples['Collision Avoidance'],
  'Modal Behavior': examples['Modal Behavior'],
  'Open Change Callbacks': examples['Open Change Callbacks'],
  'Actions Ref': examples['Actions Ref'],
  'Final Focus': examples['Final Focus'],
  'Initial Focus': examples['Initial Focus'],
  Reference: () => <ComponentReference slug="popover" />,
};
