// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/portal.examples';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  'Custom Container': { layout: 'centered' },
  'With Render Prop': { layout: 'centered' },
  'Modal Example': { layout: 'centered' },
  'Toast Notifications': { layout: 'centered' },
};

export default {
  Default: examples['Default'],
  'Custom Container': examples['Custom Container'],
  'With Render Prop': examples['With Render Prop'],
  'Modal Example': examples['Modal Example'],
  'Toast Notifications': examples['Toast Notifications'],
};
