// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/scroll-area.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  'Type (Visibility Behavior)': { layout: 'padded' },
  'Fade Edges': { layout: 'padded' },
  Size: { layout: 'padded' },
  Scrollbars: { layout: 'padded' },
  'Both Scrollbars': { layout: 'padded' },
  'Scrollable Element Ref': { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  'Type (Visibility Behavior)': examples['Type (Visibility Behavior)'],
  'Fade Edges': examples['Fade Edges'],
  Size: examples['Size'],
  Scrollbars: examples['Scrollbars'],
  'Both Scrollbars': examples['Both Scrollbars'],
  'Scrollable Element Ref': examples['Scrollable Element Ref'],
  Reference: () => <ComponentReference slug="scroll-area" />,
};
