// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/sonner.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Success: { layout: 'fullscreen' },
  Error: { layout: 'fullscreen' },
  Info: { layout: 'fullscreen' },
  Warning: { layout: 'fullscreen' },
  Loading: { layout: 'fullscreen' },
  Default: { layout: 'fullscreen' },
  'With Description': { layout: 'fullscreen' },
  'Promise Pattern': { layout: 'fullscreen' },
  'Promise Error': { layout: 'fullscreen' },
  'Promise — Conditional Toasts': { layout: 'fullscreen' },
  'Loading → Replace': { layout: 'fullscreen' },
  'Loading → Replace (Error)': { layout: 'fullscreen' },
  'File Upload with Progress': { layout: 'fullscreen' },
  'With Action': { layout: 'fullscreen' },
  'Custom Duration': { layout: 'fullscreen' },
  'Varying Heights': { layout: 'fullscreen' },
  'Custom Position (per-toast)': { layout: 'fullscreen' },
  Deduplication: { layout: 'fullscreen' },
  'Dismiss All': { layout: 'fullscreen' },
  'Custom Content': { layout: 'fullscreen' },
  'All Variants': { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Success: examples['Success'],
  Error: examples['Error'],
  Info: examples['Info'],
  Warning: examples['Warning'],
  Loading: examples['Loading'],
  Default: examples['Default'],
  'With Description': examples['With Description'],
  'Promise Pattern': examples['Promise Pattern'],
  'Promise Error': examples['Promise Error'],
  'Promise — Conditional Toasts': examples['Promise — Conditional Toasts'],
  'Loading → Replace': examples['Loading → Replace'],
  'Loading → Replace (Error)': examples['Loading → Replace (Error)'],
  'File Upload with Progress': examples['File Upload with Progress'],
  'With Action': examples['With Action'],
  'Custom Duration': examples['Custom Duration'],
  'Varying Heights': examples['Varying Heights'],
  'Custom Position (per-toast)': examples['Custom Position (per-toast)'],
  Deduplication: examples['Deduplication'],
  'Dismiss All': examples['Dismiss All'],
  'Custom Content': examples['Custom Content'],
  'All Variants': examples['All Variants'],
  Reference: () => <ComponentReference slug="sonner" />,
};
