// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/emoji-colors.examples';

export const fixtureMeta = {
  'Color for emoji': { layout: 'centered' },
  'Emoji badges': { layout: 'centered' },
  'Emoji avatars': { layout: 'centered' },
  'Picking a theme from an emoji': { layout: 'centered' },
  'Unmapped input': { layout: 'centered' },
  'All Emojis': { layout: 'centered' },
  Interactive: { layout: 'centered' },
};

export default {
  'Color for emoji': examples['Color for emoji'],
  'Emoji badges': examples['Emoji badges'],
  'Emoji avatars': examples['Emoji avatars'],
  'Picking a theme from an emoji': examples['Picking a theme from an emoji'],
  'Unmapped input': examples['Unmapped input'],
  'All Emojis': examples['All Emojis'],
  Interactive: examples['Interactive'],
};
