// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/theme.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Appearance: { layout: 'centered' },
  'Accent color': { layout: 'centered' },
  'Every accent': { layout: 'centered' },
  'Gray color': { layout: 'centered' },
  'Semantic colors': { layout: 'centered' },
  'Nested themes': { layout: 'centered' },
  'Custom accent color': { layout: 'centered' },
  'Has background': { layout: 'centered' },
  'Theme panel': { layout: 'centered' },
  Colors: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Appearance: examples['Appearance'],
  'Accent color': examples['Accent color'],
  'Every accent': examples['Every accent'],
  'Gray color': examples['Gray color'],
  'Semantic colors': examples['Semantic colors'],
  'Nested themes': examples['Nested themes'],
  'Custom accent color': examples['Custom accent color'],
  'Has background': examples['Has background'],
  'Theme panel': examples['Theme panel'],
  Colors: examples['Colors'],
  Reference: () => <ComponentReference slug="theme" />,
};
