// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/chart.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'fullscreen' },
  'Custom label': { layout: 'fullscreen' },
  Animated: { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  'Custom label': examples['Custom label'],
  Animated: examples['Animated'],
  Reference: () => <ComponentReference slug="chart" />,
};
