// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples, playgroundChildren } from '../../examples/alert.examples';
import { Alert } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Default: { layout: 'centered' },
  Color: { layout: 'centered' },
  'Semantic color': { layout: 'centered' },
  'Action render prop': { layout: 'centered' },
  'Action loading': { layout: 'centered' },
  'Action disabled': { layout: 'centered' },
  'As Alert': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Color: examples['Color'],
  'Semantic color': examples['Semantic color'],
  'Action render prop': examples['Action render prop'],
  'Action loading': examples['Action loading'],
  'Action disabled': examples['Action disabled'],
  'As Alert': examples['As Alert'],
  Playground: () => (
    <Playground slug="alert" component={Alert.Root} name="Alert.Root" renderChildren={() => playgroundChildren} />
  ),
  Reference: () => <ComponentReference slug="alert" />,
};
