// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/alert.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Color: { layout: 'centered' },
  'Semantic color': { layout: 'centered' },
  'Action render prop': { layout: 'centered' },
  'Action loading': { layout: 'centered' },
  'Action disabled': { layout: 'centered' },
  'As Alert': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Color: examples['Color'],
  'Semantic color': examples['Semantic color'],
  'Action render prop': examples['Action render prop'],
  'Action loading': examples['Action loading'],
  'Action disabled': examples['Action disabled'],
  'As Alert': examples['As Alert'],
  Reference: () => <ComponentReference slug="alert" />,
};
