// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/avatar-stack.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Default: { layout: 'centered' },
  Size: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Size: examples['Size'],
  Reference: () => <ComponentReference slug="avatar-stack" />,
};
