// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/badge.examples';
import { Badge } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Variant: { layout: 'centered' },
  Color: { layout: 'centered' },
  'Semantic color': { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Variant: examples['Variant'],
  Color: examples['Color'],
  'Semantic color': examples['Semantic color'],
  'High Contrast': examples['High Contrast'],
  Playground: () => <Playground slug="badge" component={Badge} name="Badge" />,
  Reference: () => <ComponentReference slug="badge" />,
};
