// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/breadcrumb.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  'With links': { layout: 'padded' },
  'With onClick': { layout: 'padded' },
  Truncated: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  'With links': examples['With links'],
  'With onClick': examples['With onClick'],
  Truncated: examples['Truncated'],
  Reference: () => <ComponentReference slug="breadcrumb" />,
};
