// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/card.examples';
import { Card } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Variant: { layout: 'centered' },
  'Inset Content': { layout: 'centered' },
  Media: { layout: 'centered' },
  'As another element': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Variant: examples['Variant'],
  'Inset Content': examples['Inset Content'],
  Media: examples['Media'],
  'As another element': examples['As another element'],
  Playground: () => <Playground slug="card" component={Card} name="Card" />,
  Reference: () => <ComponentReference slug="card" />,
};
