// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/carousel.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'fullscreen' },
  DynamicItems: { layout: 'fullscreen' },
  WithoutScrollSnap: { layout: 'fullscreen' },
  ImperativeScrollTo: { layout: 'fullscreen' },
  Vertical: { layout: 'fullscreen' },
  DefaultValue: { layout: 'fullscreen' },
  StepByItem: { layout: 'fullscreen' },
  StepByItemNoSnap: { layout: 'fullscreen' },
  ProductGallery: { layout: 'fullscreen' },
  Loop: { layout: 'fullscreen' },
  LoopStepByItem: { layout: 'fullscreen' },
  ResizableViewport: { layout: 'fullscreen' },
  SnapToCenter: { layout: 'fullscreen' },
  'Controlled (value)': { layout: 'fullscreen' },
  ScrollBehavior: { layout: 'fullscreen' },
  Testimonials: { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  DynamicItems: examples['DynamicItems'],
  WithoutScrollSnap: examples['WithoutScrollSnap'],
  ImperativeScrollTo: examples['ImperativeScrollTo'],
  Vertical: examples['Vertical'],
  DefaultValue: examples['DefaultValue'],
  StepByItem: examples['StepByItem'],
  StepByItemNoSnap: examples['StepByItemNoSnap'],
  ProductGallery: examples['ProductGallery'],
  Loop: examples['Loop'],
  LoopStepByItem: examples['LoopStepByItem'],
  ResizableViewport: examples['ResizableViewport'],
  SnapToCenter: examples['SnapToCenter'],
  'Controlled (value)': examples['Controlled (value)'],
  ScrollBehavior: examples['ScrollBehavior'],
  Testimonials: examples['Testimonials'],
  Reference: () => <ComponentReference slug="carousel" />,
};
