// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/credit-card.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Default: { layout: 'centered' },
  Controlled: { layout: 'centered' },
  'ljkui Card': { layout: 'centered' },
  'Custom Design': { layout: 'centered' },
  'Back Only': { layout: 'centered' },
  'Input States': { layout: 'centered' },
  'Form Integration': { layout: 'centered' },
  Colors: { layout: 'centered' },
  'Per-Face Colors': { layout: 'centered' },
  'Card Brands': { layout: 'centered' },
  'Provider Detection': { layout: 'centered' },
  'Custom Fields': { layout: 'centered' },
  'Whop Card': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Controlled: examples['Controlled'],
  'ljkui Card': examples['ljkui Card'],
  'Custom Design': examples['Custom Design'],
  'Back Only': examples['Back Only'],
  'Input States': examples['Input States'],
  'Form Integration': examples['Form Integration'],
  Colors: examples['Colors'],
  'Per-Face Colors': examples['Per-Face Colors'],
  'Card Brands': examples['Card Brands'],
  'Provider Detection': examples['Provider Detection'],
  'Custom Fields': examples['Custom Fields'],
  'Whop Card': examples['Whop Card'],
  Reference: () => <ComponentReference slug="credit-card" />,
};
