// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/dialog.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Default: { layout: 'centered' },
  Sizes: { layout: 'centered' },
  'With inset content': { layout: 'centered' },
  'Detached Triggers': { layout: 'centered' },
  'Multiple Triggers with Payload': { layout: 'centered' },
  'Controlled Mode': { layout: 'centered' },
  'Actions Ref': { layout: 'centered' },
  'Initial Focus': { layout: 'centered' },
  'Final Focus': { layout: 'centered' },
  'Open Change Callbacks': { layout: 'centered' },
  'Nested Dialogs': { layout: 'centered' },
  'Close Confirmation': { layout: 'centered' },
  'With Popover and HoverCard': { layout: 'centered' },
  'Dialog from Dropdown Menu': { layout: 'centered' },
  'Dialog Trigger in Dropdown Menu': { layout: 'centered' },
  'Dialog detached trigger in Dropdown Menu using handle': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Sizes: examples['Sizes'],
  'With inset content': examples['With inset content'],
  'Detached Triggers': examples['Detached Triggers'],
  'Multiple Triggers with Payload': examples['Multiple Triggers with Payload'],
  'Controlled Mode': examples['Controlled Mode'],
  'Actions Ref': examples['Actions Ref'],
  'Initial Focus': examples['Initial Focus'],
  'Final Focus': examples['Final Focus'],
  'Open Change Callbacks': examples['Open Change Callbacks'],
  'Nested Dialogs': examples['Nested Dialogs'],
  'Close Confirmation': examples['Close Confirmation'],
  'With Popover and HoverCard': examples['With Popover and HoverCard'],
  'Dialog from Dropdown Menu': examples['Dialog from Dropdown Menu'],
  'Dialog Trigger in Dropdown Menu': examples['Dialog Trigger in Dropdown Menu'],
  'Dialog detached trigger in Dropdown Menu using handle':
    examples['Dialog detached trigger in Dropdown Menu using handle'],
  Reference: () => <ComponentReference slug="dialog" />,
};
