// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/drawer.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'fullscreen' },
  Default: { layout: 'fullscreen' },
  'With inset content': { layout: 'fullscreen' },
  'Detached Triggers': { layout: 'fullscreen' },
  'Multiple Triggers with Payload': { layout: 'fullscreen' },
  'Controlled Mode': { layout: 'fullscreen' },
  'Actions Ref': { layout: 'fullscreen' },
  'Initial Focus': { layout: 'fullscreen' },
  'Final Focus': { layout: 'fullscreen' },
  'Open Change Callbacks': { layout: 'fullscreen' },
  'Keep Mounted': { layout: 'fullscreen' },
  'Nested Drawers': { layout: 'fullscreen' },
  'Deeply Nested Drawers': { layout: 'fullscreen' },
  'With Popover, Select, Dropdown, and HoverCard': { layout: 'fullscreen' },
  'With Dialog Inside': { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'With inset content': examples['With inset content'],
  'Detached Triggers': examples['Detached Triggers'],
  'Multiple Triggers with Payload': examples['Multiple Triggers with Payload'],
  'Controlled Mode': examples['Controlled Mode'],
  'Actions Ref': examples['Actions Ref'],
  'Initial Focus': examples['Initial Focus'],
  'Final Focus': examples['Final Focus'],
  'Open Change Callbacks': examples['Open Change Callbacks'],
  'Keep Mounted': examples['Keep Mounted'],
  'Nested Drawers': examples['Nested Drawers'],
  'Deeply Nested Drawers': examples['Deeply Nested Drawers'],
  'With Popover, Select, Dropdown, and HoverCard': examples['With Popover, Select, Dropdown, and HoverCard'],
  'With Dialog Inside': examples['With Dialog Inside'],
  Reference: () => <ComponentReference slug="drawer" />,
};
