// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/empty.examples';

export const fixtureMeta = {
  Default: { layout: 'padded' },
  SearchResults: { layout: 'padded' },
  Minimal: { layout: 'padded' },
  Colors: { layout: 'padded' },
  Emojis: { layout: 'padded' },
  ShinyEmojis: { layout: 'padded' },
  WithAvatar: { layout: 'padded' },
  WithAvatarStack: { layout: 'padded' },
  WithTextFieldAndButton: { layout: 'padded' },
  WithCheckbox: { layout: 'padded' },
  FileDropHint: { layout: 'padded' },
  ErrorWithRetry: { layout: 'padded' },
  Achievement: { layout: 'padded' },
  WithKeyboardShortcut: { layout: 'padded' },
  WithOTPField: { layout: 'padded' },
  NotFound404: { layout: 'padded' },
  AIAssistant: { layout: 'padded' },
  UpgradeToPro: { layout: 'padded' },
};

export default {
  Default: examples['Default'],
  SearchResults: examples['SearchResults'],
  Minimal: examples['Minimal'],
  Colors: examples['Colors'],
  Emojis: examples['Emojis'],
  ShinyEmojis: examples['ShinyEmojis'],
  WithAvatar: examples['WithAvatar'],
  WithAvatarStack: examples['WithAvatarStack'],
  WithTextFieldAndButton: examples['WithTextFieldAndButton'],
  WithCheckbox: examples['WithCheckbox'],
  FileDropHint: examples['FileDropHint'],
  ErrorWithRetry: examples['ErrorWithRetry'],
  Achievement: examples['Achievement'],
  WithKeyboardShortcut: examples['WithKeyboardShortcut'],
  WithOTPField: examples['WithOTPField'],
  NotFound404: examples['NotFound404'],
  AIAssistant: examples['AIAssistant'],
  UpgradeToPro: examples['UpgradeToPro'],
};
