// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/hover-card.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Size: { layout: 'centered' },
  'With inset content': { layout: 'centered' },
  'Custom Delays': { layout: 'centered' },
  'Controlled Mode': { layout: 'centered' },
  Positioning: { layout: 'centered' },
  'Profile Card (Real World)': { layout: 'centered' },
  'Link Preview': { layout: 'centered' },
  'Open Change Complete Callback': { layout: 'centered' },
  'Custom Anchor': { layout: 'centered' },
  'With Button Trigger': { layout: 'centered' },
  'Collision Boundary': { layout: 'centered' },
  'Collision Avoidance': { layout: 'centered' },
  Sticky: { layout: 'centered' },
  'Disable Anchor Tracking': { layout: 'centered' },
  'Multiple Triggers': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Size: examples['Size'],
  'With inset content': examples['With inset content'],
  'Custom Delays': examples['Custom Delays'],
  'Controlled Mode': examples['Controlled Mode'],
  Positioning: examples['Positioning'],
  'Profile Card (Real World)': examples['Profile Card (Real World)'],
  'Link Preview': examples['Link Preview'],
  'Open Change Complete Callback': examples['Open Change Complete Callback'],
  'Custom Anchor': examples['Custom Anchor'],
  'With Button Trigger': examples['With Button Trigger'],
  'Collision Boundary': examples['Collision Boundary'],
  'Collision Avoidance': examples['Collision Avoidance'],
  Sticky: examples['Sticky'],
  'Disable Anchor Tracking': examples['Disable Anchor Tracking'],
  'Multiple Triggers': examples['Multiple Triggers'],
  Reference: () => <ComponentReference slug="hover-card" />,
};
