// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/item.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Default: { layout: 'padded' },
  Group: { layout: 'padded' },
  Variants: { layout: 'padded' },
  Sizes: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Group: examples['Group'],
  Variants: examples['Variants'],
  Sizes: examples['Sizes'],
  Reference: () => <ComponentReference slug="item" />,
};
