// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/meter.examples';
import { Meter } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  'Optimum coloring': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Color: examples['Color'],
  'Optimum coloring': examples['Optimum coloring'],
  Playground: () => <Playground slug="meter" component={Meter} name="Meter" />,
  Reference: () => <ComponentReference slug="meter" />,
};
