// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/oscar.examples';

export const fixtureMeta = {
  'Oscar’s profile': { layout: 'fullscreen' },
  'Oscar’s badges': { layout: 'fullscreen' },
  'Oscar’s guest list': { layout: 'fullscreen' },
  'Oscar’s shortlist': { layout: 'fullscreen' },
  'Oscar’s ballot': { layout: 'fullscreen' },
  'Oscar’s campaign progress': { layout: 'fullscreen' },
  'Oscar’s preferences': { layout: 'fullscreen' },
  'Oscar’s announcement': { layout: 'fullscreen' },
  'Oscar’s categories': { layout: 'fullscreen' },
  'Oscar’s acceptance speech': { layout: 'fullscreen' },
  'Oscar’s shortcuts': { layout: 'fullscreen' },
  'No Oscars found': { layout: 'fullscreen' },
};

export default {
  'Oscar’s profile': examples['Oscar’s profile'],
  'Oscar’s badges': examples['Oscar’s badges'],
  'Oscar’s guest list': examples['Oscar’s guest list'],
  'Oscar’s shortlist': examples['Oscar’s shortlist'],
  'Oscar’s ballot': examples['Oscar’s ballot'],
  'Oscar’s campaign progress': examples['Oscar’s campaign progress'],
  'Oscar’s preferences': examples['Oscar’s preferences'],
  'Oscar’s announcement': examples['Oscar’s announcement'],
  'Oscar’s categories': examples['Oscar’s categories'],
  'Oscar’s acceptance speech': examples['Oscar’s acceptance speech'],
  'Oscar’s shortcuts': examples['Oscar’s shortcuts'],
  'No Oscars found': examples['No Oscars found'],
};
