// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/overlay.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Example: { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Example: examples['Example'],
  Reference: () => <ComponentReference slug="overlay" />,
};
