// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/sheet.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'fullscreen' },
  Default: { layout: 'fullscreen' },
  Nested: { layout: 'fullscreen' },
  'With inset content': { layout: 'fullscreen' },
  'Scrollable content': { layout: 'fullscreen' },
  'Controlled (non dismissable)': { layout: 'fullscreen' },
  'Initial Focus': { layout: 'fullscreen' },
  'Final Focus': { layout: 'fullscreen' },
  'Prevent Focus on Close': { layout: 'fullscreen' },
  'Controlled with Form': { layout: 'fullscreen' },
  'Open Change Callbacks': { layout: 'fullscreen' },
  'Close Confirmation': { layout: 'fullscreen' },
  'Sheet from Dropdown Menu': { layout: 'fullscreen' },
  'Sheet Trigger in Dropdown Menu': { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Nested: examples['Nested'],
  'With inset content': examples['With inset content'],
  'Scrollable content': examples['Scrollable content'],
  'Controlled (non dismissable)': examples['Controlled (non dismissable)'],
  'Initial Focus': examples['Initial Focus'],
  'Final Focus': examples['Final Focus'],
  'Prevent Focus on Close': examples['Prevent Focus on Close'],
  'Controlled with Form': examples['Controlled with Form'],
  'Open Change Callbacks': examples['Open Change Callbacks'],
  'Close Confirmation': examples['Close Confirmation'],
  'Sheet from Dropdown Menu': examples['Sheet from Dropdown Menu'],
  'Sheet Trigger in Dropdown Menu': examples['Sheet Trigger in Dropdown Menu'],
  Reference: () => <ComponentReference slug="sheet" />,
};
