// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/skeleton.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Avatar: { layout: 'centered' },
  'Box (auto-size from content)': { layout: 'centered' },
  'Box (loaded vs loading)': { layout: 'centered' },
  'Avatar sizes': { layout: 'centered' },
  'Avatar colors': { layout: 'centered' },
  'Avatar high contrast': { layout: 'centered' },
  Text: { layout: 'centered' },
  'Text sizes': { layout: 'centered' },
  'Text colors': { layout: 'centered' },
  'Text high contrast': { layout: 'centered' },
  Rect: { layout: 'centered' },
  'Rect colors': { layout: 'centered' },
  'Rect high contrast': { layout: 'centered' },
  'Synced animation': { layout: 'centered' },
  Composed: { layout: 'centered' },
  'Composed color': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Avatar: examples['Avatar'],
  'Box (auto-size from content)': examples['Box (auto-size from content)'],
  'Box (loaded vs loading)': examples['Box (loaded vs loading)'],
  'Avatar sizes': examples['Avatar sizes'],
  'Avatar colors': examples['Avatar colors'],
  'Avatar high contrast': examples['Avatar high contrast'],
  Text: examples['Text'],
  'Text sizes': examples['Text sizes'],
  'Text colors': examples['Text colors'],
  'Text high contrast': examples['Text high contrast'],
  Rect: examples['Rect'],
  'Rect colors': examples['Rect colors'],
  'Rect high contrast': examples['Rect high contrast'],
  'Synced animation': examples['Synced animation'],
  Composed: examples['Composed'],
  'Composed color': examples['Composed color'],
  Reference: () => <ComponentReference slug="skeleton" />,
};
