// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/spinner.examples';
import { Spinner } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  'With children': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  'With children': examples['With children'],
  Playground: () => <Playground slug="spinner" component={Spinner} name="Spinner" />,
  Reference: () => <ComponentReference slug="spinner" />,
};
