// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/stepper.examples';
import { Stepper } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Horizontal: { layout: 'centered' },
  Vertical: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Horizontal: examples['Horizontal'],
  Vertical: examples['Vertical'],
  Size: examples['Size'],
  Color: examples['Color'],
  Playground: () => <Playground slug="stepper" component={Stepper} name="Stepper" />,
  Reference: () => <ComponentReference slug="stepper" />,
};
