// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/tabs.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Default: { layout: 'padded' },
  Size: { layout: 'padded' },
  Color: { layout: 'padded' },
  'High Contrast': { layout: 'padded' },
  'Activate on Focus': { layout: 'padded' },
  'Keep Mounted': { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Size: examples['Size'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  'Activate on Focus': examples['Activate on Focus'],
  'Keep Mounted': examples['Keep Mounted'],
  Reference: () => <ComponentReference slug="tabs" />,
};
