// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/tabs-nav.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Size: { layout: 'padded' },
  Color: { layout: 'padded' },
  'High Contrast': { layout: 'padded' },
  'Render Prop (Client-Side Routing)': { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  'Render Prop (Client-Side Routing)': examples['Render Prop (Client-Side Routing)'],
  Reference: () => <ComponentReference slug="tabs-nav" />,
};
