// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/tooltip.examples';
import { Tooltip } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  'With Provider (Group Delay)': { layout: 'centered' },
  Positioning: { layout: 'centered' },
  'Custom Delay': { layout: 'centered' },
  'Disable Hoverable Popup': { layout: 'centered' },
  'Close on Click': { layout: 'centered' },
  Disabled: { layout: 'centered' },
  'Controlled Mode': { layout: 'centered' },
  'Side Offset': { layout: 'centered' },
  'Track Cursor Axis': { layout: 'centered' },
  'Open Change Complete Callback': { layout: 'centered' },
  'Actions Ref': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  'With Provider (Group Delay)': examples['With Provider (Group Delay)'],
  Positioning: examples['Positioning'],
  'Custom Delay': examples['Custom Delay'],
  'Disable Hoverable Popup': examples['Disable Hoverable Popup'],
  'Close on Click': examples['Close on Click'],
  Disabled: examples['Disabled'],
  'Controlled Mode': examples['Controlled Mode'],
  'Side Offset': examples['Side Offset'],
  'Track Cursor Axis': examples['Track Cursor Axis'],
  'Open Change Complete Callback': examples['Open Change Complete Callback'],
  'Actions Ref': examples['Actions Ref'],
  Playground: () => <Playground slug="tooltip" component={Tooltip} name="Tooltip" />,
  Reference: () => <ComponentReference slug="tooltip" />,
};
