// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/tree-view.examples';
import { TreeView } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Size: examples['Size'],
  Color: examples['Color'],
  Playground: () => <Playground slug="tree-view" component={TreeView} name="TreeView" />,
  Reference: () => <ComponentReference slug="tree-view" />,
};
