// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/visually-hidden.examples';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Default: { layout: 'centered' },
  'Icon Button with Label': { layout: 'centered' },
  'Skip Link': { layout: 'centered' },
  'Form Labels': { layout: 'centered' },
  'With Render Prop': { layout: 'centered' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'Icon Button with Label': examples['Icon Button with Label'],
  'Skip Link': examples['Skip Link'],
  'Form Labels': examples['Form Labels'],
  'With Render Prop': examples['With Render Prop'],
};
