// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/widget-stack.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Orientation: { layout: 'padded' },
  SingleWidget: { layout: 'padded' },
  WithControls: { layout: 'padded' },
  AutoPlay: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Orientation: examples['Orientation'],
  SingleWidget: examples['SingleWidget'],
  WithControls: examples['WithControls'],
  AutoPlay: examples['AutoPlay'],
  Reference: () => <ComponentReference slug="widget-stack" />,
};
