// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/bleed.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Example: { layout: 'centered' },
  Side: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Example: examples['Example'],
  Side: examples['Side'],
  Reference: () => <ComponentReference slug="bleed" />,
};
