// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/resizable.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Horizontal: { layout: 'fullscreen' },
  Vertical: { layout: 'fullscreen' },
  'Three panels': { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Horizontal: examples['Horizontal'],
  Vertical: examples['Vertical'],
  'Three panels': examples['Three panels'],
  Reference: () => <ComponentReference slug="resizable" />,
};
