// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/section.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  'As another element': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  'As another element': examples['As another element'],
  Reference: () => <ComponentReference slug="section" />,
};
