// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/separator.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  Orientation: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Color: examples['Color'],
  Orientation: examples['Orientation'],
  Reference: () => <ComponentReference slug="separator" />,
};
