// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../../examples/date-range-picker.examples';
import { ComponentReference } from '../../../fixture-support/reference';

export const fixtureMeta = {
  Sizes: { layout: 'centered' },
  Custom: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Sizes: examples['Sizes'],
  Custom: examples['Custom'],
  Reference: () => <ComponentReference slug="date-range-picker" />,
};
