// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../../examples/date-field.examples';
import { ComponentReference } from '../../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  MinValue: { layout: 'centered' },
  'With time': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  MinValue: examples['MinValue'],
  'With time': examples['With time'],
  Reference: () => <ComponentReference slug="date-field" />,
};
