// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { fixtures } from '../../fixture-support/tools/ColorScale';

export const fixtureMeta = {
  Accent: { layout: 'fullscreen' },
  Gray: { layout: 'fullscreen' },
  Semantic: { layout: 'fullscreen' },
  'All palettes': { layout: 'fullscreen' },
};

export default {
  Accent: fixtures['Accent'],
  Gray: fixtures['Gray'],
  Semantic: fixtures['Semantic'],
  'All palettes': fixtures['All palettes'],
};
