// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/button.examples';
import { Button } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Size: { layout: 'centered' },
  Variant: { layout: 'centered' },
  Color: { layout: 'centered' },
  'Semantic color': { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  'With Icons': { layout: 'centered' },
  Loading: { layout: 'centered' },
  'Render as Different Element': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Variant: examples['Variant'],
  Color: examples['Color'],
  'Semantic color': examples['Semantic color'],
  'High Contrast': examples['High Contrast'],
  'With Icons': examples['With Icons'],
  Loading: examples['Loading'],
  'Render as Different Element': examples['Render as Different Element'],
  Playground: () => <Playground slug="button" component={Button} name="Button" />,
  Reference: () => <ComponentReference slug="button" />,
};
