// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/command.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'fullscreen' },
  Default: { layout: 'fullscreen' },
  'With selection': { layout: 'fullscreen' },
  'In a dialog': { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'With selection': examples['With selection'],
  'In a dialog': examples['In a dialog'],
  Reference: () => <ComponentReference slug="command" />,
};
