// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/context-menu.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Default: { layout: 'centered' },
  'Checkbox and Radio Items': { layout: 'centered' },
  'Nested Menu': { layout: 'centered' },
  'Item as Link': { layout: 'centered' },
  'Dialog from Context Menu': { layout: 'centered' },
  'Side and Align': { layout: 'centered' },
  'Side Offset and Align Offset': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'Checkbox and Radio Items': examples['Checkbox and Radio Items'],
  'Nested Menu': examples['Nested Menu'],
  'Item as Link': examples['Item as Link'],
  'Dialog from Context Menu': examples['Dialog from Context Menu'],
  'Side and Align': examples['Side and Align'],
  'Side Offset and Align Offset': examples['Side Offset and Align Offset'],
  Reference: () => <ComponentReference slug="context-menu" />,
};
