// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/dropdown-menu.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Default: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  'Open on Hover': { layout: 'centered' },
  'Item as Link': { layout: 'centered' },
  'Detached Triggers': { layout: 'centered' },
  'Multiple Triggers': { layout: 'centered' },
  'Controlled Mode with Multiple Triggers': { layout: 'centered' },
  'Side and Align': { layout: 'centered' },
  'Side Offset and Align Offset': { layout: 'centered' },
  'Many Adjacent Submenus': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  Size: examples['Size'],
  Color: examples['Color'],
  'Open on Hover': examples['Open on Hover'],
  'Item as Link': examples['Item as Link'],
  'Detached Triggers': examples['Detached Triggers'],
  'Multiple Triggers': examples['Multiple Triggers'],
  'Controlled Mode with Multiple Triggers': examples['Controlled Mode with Multiple Triggers'],
  'Side and Align': examples['Side and Align'],
  'Side Offset and Align Offset': examples['Side Offset and Align Offset'],
  'Many Adjacent Submenus': examples['Many Adjacent Submenus'],
  Reference: () => <ComponentReference slug="dropdown-menu" />,
};
