// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/icon-button.examples';
import { IconButton } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Size: { layout: 'centered' },
  Variant: { layout: 'centered' },
  Color: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  Loading: { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Variant: examples['Variant'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  Loading: examples['Loading'],
  Playground: () => <Playground slug="icon-button" component={IconButton} name="IconButton" />,
  Reference: () => <ComponentReference slug="icon-button" />,
};
