// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/input-otp.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  Pattern: { layout: 'centered' },
  Separator: { layout: 'centered' },
  Controlled: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Pattern: examples['Pattern'],
  Separator: examples['Separator'],
  Controlled: examples['Controlled'],
  Reference: () => <ComponentReference slug="input-otp" />,
};
