// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/navigation-menu.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'fullscreen' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  Reference: () => <ComponentReference slug="navigation-menu" />,
};
