// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/pagination.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  Default: { layout: 'padded' },
  'With ellipsis': { layout: 'padded' },
  Sizes: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'With ellipsis': examples['With ellipsis'],
  Sizes: examples['Sizes'],
  Reference: () => <ComponentReference slug="pagination" />,
};
