// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/select.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  TriggerVariant: { layout: 'centered' },
  Color: { layout: 'centered' },
  Placeholder: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  'Formatting the Value': { layout: 'centered' },
  'Dropdown Positioning': { layout: 'centered' },
  'Side and Align': { layout: 'centered' },
  'Side Offset and Align Offset': { layout: 'centered' },
  'Controlled Mode': { layout: 'centered' },
  'Many Items': { layout: 'centered' },
  'Multiple Selection': { layout: 'centered' },
  Controlled: { layout: 'centered' },
  'Object Values': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  TriggerVariant: examples['TriggerVariant'],
  Color: examples['Color'],
  Placeholder: examples['Placeholder'],
  'High Contrast': examples['High Contrast'],
  'Formatting the Value': examples['Formatting the Value'],
  'Dropdown Positioning': examples['Dropdown Positioning'],
  'Side and Align': examples['Side and Align'],
  'Side Offset and Align Offset': examples['Side Offset and Align Offset'],
  'Controlled Mode': examples['Controlled Mode'],
  'Many Items': examples['Many Items'],
  'Multiple Selection': examples['Multiple Selection'],
  Controlled: examples['Controlled'],
  'Object Values': examples['Object Values'],
  Reference: () => <ComponentReference slug="select" />,
};
