// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/slider.examples';
import { Slider } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  Range: { layout: 'centered' },
  Orientation: { layout: 'centered' },
  'Value Callbacks': { layout: 'centered' },
  'Min Steps Between Values': { layout: 'centered' },
  'Input Ref': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Size: examples['Size'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  Range: examples['Range'],
  Orientation: examples['Orientation'],
  'Value Callbacks': examples['Value Callbacks'],
  'Min Steps Between Values': examples['Min Steps Between Values'],
  'Input Ref': examples['Input Ref'],
  Playground: () => <Playground slug="slider" component={Slider} name="Slider" />,
  Reference: () => <ComponentReference slug="slider" />,
};
