// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/switch.examples';
import { Switch } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  'High Contrast': { layout: 'centered' },
  'Alignment with text': { layout: 'centered' },
  'Form with uncheckedValue': { layout: 'centered' },
  'Read Only': { layout: 'centered' },
  'Input Ref': { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Color: examples['Color'],
  'High Contrast': examples['High Contrast'],
  'Alignment with text': examples['Alignment with text'],
  'Form with uncheckedValue': examples['Form with uncheckedValue'],
  'Read Only': examples['Read Only'],
  'Input Ref': examples['Input Ref'],
  Playground: () => <Playground slug="switch" component={Switch} name="Switch" />,
  Reference: () => <ComponentReference slug="switch" />,
};
