// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/textarea.examples';
import { Textarea } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Size: { layout: 'centered' },
  Variant: { layout: 'centered' },
  Color: { layout: 'centered' },
  Playground: { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  Size: examples['Size'],
  Variant: examples['Variant'],
  Color: examples['Color'],
  Playground: () => <Playground slug="textarea" component={Textarea} name="Textarea" />,
  Reference: () => <ComponentReference slug="textarea" />,
};
