// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/toggle-group-nav.examples';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Default: { layout: 'centered' },
  'Render Prop (Client-Side Routing)': { layout: 'centered' },
};

export default {
  Overview: examples['Overview'],
  Default: examples['Default'],
  'Render Prop (Client-Side Routing)': examples['Render Prop (Client-Side Routing)'],
};
