// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/toggle-group-radio-group.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  'Input Ref': { layout: 'centered' },
  Controlled: { layout: 'centered' },
  'Type-Safe Values': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  'Input Ref': examples['Input Ref'],
  Controlled: examples['Controlled'],
  'Type-Safe Values': examples['Type-Safe Values'],
  Reference: () => <ComponentReference slug="toggle-group-radio-group" />,
};
