// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/toggle-group.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'centered' },
  'In a drawer': { layout: 'centered' },
  'Activate on Focus': { layout: 'centered' },
  'Keep Mounted': { layout: 'centered' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  'In a drawer': examples['In a drawer'],
  'Activate on Focus': examples['Activate on Focus'],
  'Keep Mounted': examples['Keep Mounted'],
  Reference: () => <ComponentReference slug="toggle-group" />,
};
