// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { fixtures } from '../../fixture-support/tools/IconBrowser';

export const fixtureMeta = {
  'Icon Browser': { layout: 'fullscreen' },
  'Provider Size Comparison': { layout: 'fullscreen' },
};

export default {
  'Icon Browser': fixtures['Icon Browser'],
  'Provider Size Comparison': fixtures['Provider Size Comparison'],
};
