// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { fixtures } from '../../fixture-support/tools/ThemePlayground';

export const fixtureMeta = {
  'Theme Playground': { layout: 'fullscreen' },
};

export default {
  'Theme Playground': fixtures['Theme Playground'],
};
