// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/icons.examples';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  'Built-in icons': { layout: 'centered' },
  'Adapter (lucide)': { layout: 'centered' },
  Size: { layout: 'centered' },
  Color: { layout: 'centered' },
  'In components': { layout: 'centered' },
  'Icon browser': { layout: 'centered' },
};

export default {
  Overview: examples['Overview'],
  'Built-in icons': examples['Built-in icons'],
  'Adapter (lucide)': examples['Adapter (lucide)'],
  Size: examples['Size'],
  Color: examples['Color'],
  'In components': examples['In components'],
  'Icon browser': examples['Icon browser'],
};
