// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/scrollbars.examples';

export const fixtureMeta = {
  'Hidden by default': { layout: 'centered' },
  'Thin scrollbar': { layout: 'centered' },
  Horizontal: { layout: 'centered' },
  'Both axes': { layout: 'centered' },
  'In a card': { layout: 'centered' },
};

export default {
  'Hidden by default': examples['Hidden by default'],
  'Thin scrollbar': examples['Thin scrollbar'],
  Horizontal: examples['Horizontal'],
  'Both axes': examples['Both axes'],
  'In a card': examples['In a card'],
};
