// GENERATED by scripts/gen-fixtures.ts — do not edit.
import { examples } from '../../examples/shine.examples';

export const fixtureMeta = {
  Overview: { layout: 'centered' },
  Example: { layout: 'centered' },
};

export default {
  Overview: examples['Overview'],
  Example: examples['Example'],
};
