// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/field.examples';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Default: { layout: 'padded' },
  'With Fieldset': { layout: 'padded' },
  'Fieldset Disabled': { layout: 'padded' },
  'With Input': { layout: 'padded' },
  'With Select': { layout: 'padded' },
  'With Slider (Range Validation)': { layout: 'padded' },
  'With Slider (Budget)': { layout: 'padded' },
  'With Combobox': { layout: 'padded' },
  'With Autocomplete': { layout: 'padded' },
  'With NumberField': { layout: 'padded' },
  'With Switch': { layout: 'padded' },
  'With RadioGroup': { layout: 'padded' },
  'With Checkbox': { layout: 'padded' },
  'With Slider': { layout: 'padded' },
  'Custom Validation': { layout: 'padded' },
  'Complete Form Example': { layout: 'padded' },
  'Field Custom Validation': { layout: 'padded' },
  Validity: { layout: 'padded' },
  'Disabled State': { layout: 'padded' },
  'All Validity States': { layout: 'padded' },
  'With TextField': { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Default: examples['Default'],
  'With Fieldset': examples['With Fieldset'],
  'Fieldset Disabled': examples['Fieldset Disabled'],
  'With Input': examples['With Input'],
  'With Select': examples['With Select'],
  'With Slider (Range Validation)': examples['With Slider (Range Validation)'],
  'With Slider (Budget)': examples['With Slider (Budget)'],
  'With Combobox': examples['With Combobox'],
  'With Autocomplete': examples['With Autocomplete'],
  'With NumberField': examples['With NumberField'],
  'With Switch': examples['With Switch'],
  'With RadioGroup': examples['With RadioGroup'],
  'With Checkbox': examples['With Checkbox'],
  'With Slider': examples['With Slider'],
  'Custom Validation': examples['Custom Validation'],
  'Complete Form Example': examples['Complete Form Example'],
  'Field Custom Validation': examples['Field Custom Validation'],
  Validity: examples['Validity'],
  'Disabled State': examples['Disabled State'],
  'All Validity States': examples['All Validity States'],
  'With TextField': examples['With TextField'],
  Reference: () => <ComponentReference slug="field" />,
};
