// GENERATED by scripts/gen-fixtures.ts — do not edit.
import * as React from 'react';
import { examples } from '../../examples/form.examples';
import { Form } from 'ljkui';
import { Playground } from '../../fixture-support/playground';
import { ComponentReference } from '../../fixture-support/reference';

export const fixtureMeta = {
  Overview: { layout: 'padded' },
  'Getting Started': { layout: 'padded' },
  'Constraint Validation': { layout: 'padded' },
  'Required Controls': { layout: 'padded' },
  'Displaying Errors': { layout: 'padded' },
  'Form Reset': { layout: 'padded' },
  'Submit form values as a JavaScript object': { layout: 'padded' },
  'Server-side Validation': { layout: 'padded' },
  'Conditional Fields': { layout: 'padded' },
  'Dynamic Form Fields': { layout: 'padded' },
  'Dirty State Warning': { layout: 'padded' },
  'Auto-save Form': { layout: 'padded' },
  'Multi-step Wizard Form': { layout: 'padded' },
  'Using with Zod': { layout: 'padded' },
  'Submit with a Server Function': { layout: 'padded' },
  'Form Library Field Binding': { layout: 'padded' },
  'TanStack Form Integration': { layout: 'padded' },
  Playground: { layout: 'padded' },
  Reference: { layout: 'fullscreen' },
};

export default {
  Overview: examples['Overview'],
  'Getting Started': examples['Getting Started'],
  'Constraint Validation': examples['Constraint Validation'],
  'Required Controls': examples['Required Controls'],
  'Displaying Errors': examples['Displaying Errors'],
  'Form Reset': examples['Form Reset'],
  'Submit form values as a JavaScript object': examples['Submit form values as a JavaScript object'],
  'Server-side Validation': examples['Server-side Validation'],
  'Conditional Fields': examples['Conditional Fields'],
  'Dynamic Form Fields': examples['Dynamic Form Fields'],
  'Dirty State Warning': examples['Dirty State Warning'],
  'Auto-save Form': examples['Auto-save Form'],
  'Multi-step Wizard Form': examples['Multi-step Wizard Form'],
  'Using with Zod': examples['Using with Zod'],
  'Submit with a Server Function': examples['Submit with a Server Function'],
  'Form Library Field Binding': examples['Form Library Field Binding'],
  'TanStack Form Integration': examples['TanStack Form Integration'],
  Playground: () => <Playground slug="form" component={Form} name="Form" />,
  Reference: () => <ComponentReference slug="form" />,
};
